spring:
  application:
    name: auth-service
jwt:
  issuer: banking-auth-service
  audience: banking-api
  clock-skew-seconds: 30

# LOCAL DEVELOPMENT ONLY
  private-key-location: classpath:private-key.pem
  public-key-location: classpath:public-key.pem

  access-token-expiration-seconds: 900