version: '3.8'

services:

  # =========================================================
  # REDIS
  # =========================================================
  redis:
    image: redis:latest
    container_name: redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - banking-network


  # =========================================================
  # POSTGRESQL - AUTH SERVICE
  # =========================================================
  postgres-auth:
    image: postgres:18
    container_name: postgres-auth

    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10

    ports:
      - "5432:5432"

    volumes:
      - postgres-auth-data:/var/lib/postgresql

    networks:
      - banking-network


  # =========================================================
  # POSTGRESQL - TRANSACTION SERVICE
  # =========================================================
  postgres-transaction:
    image: postgres:18
    container_name: postgres-transaction

    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10

    ports:
      - "5433:5432"

    volumes:
      - postgres-transaction-data:/var/lib/postgresql

    networks:
      - banking-network



  # =========================================================
  # POSTGRESQL - ACCOUNT SERVICE
  # =========================================================
  postgres-account:
    image: postgres:18
    container_name: postgres-account

    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10

    ports:
      - "5434:5432"

    volumes:
      - postgres-account-data:/var/lib/postgresql

    networks:
      - banking-network


  # =========================================================
  # KAFKA - KRaft MODE
  # =========================================================
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    hostname: kafka

    ports:
      - "9092:9092"

    environment:

      # -----------------------------
      # KRaft
      # -----------------------------
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"


      # -----------------------------
      # Listeners
      # -----------------------------
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        CONTROLLER:PLAINTEXT,
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT

      KAFKA_LISTENERS: >
        CONTROLLER://0.0.0.0:9093,
        PLAINTEXT://0.0.0.0:29092,
        PLAINTEXT_HOST://0.0.0.0:9092

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka:29092,
        PLAINTEXT_HOST://localhost:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"


      # -----------------------------
      # Kafka Cluster
      # -----------------------------
      CLUSTER_ID: "EmptNWtoR4GGWx-BH6nGLQ"


      # -----------------------------
      # Single broker settings
      # -----------------------------
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_MIN_INSYNC_REPLICAS: 1

      KAFKA_DEFAULT_REPLICATION_FACTOR: 1


      # -----------------------------
      # Development
      # -----------------------------
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    networks:
      - banking-network


  # =========================================================
  # KAFKA UI
  # =========================================================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui

    ports:
      - "8000:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: local

      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

    depends_on:
      - kafka

    networks:
      - banking-network


  # =========================================================
  # DEBEZIUM + KAFKA CONNECT
  # =========================================================
  debezium-connect:
    image: quay.io/debezium/connect:3.6
    container_name: debezium-connect

    depends_on:
      - kafka
      - postgres-transaction

    ports:
      - "8083:8083"

    environment:

      # -----------------------------
      # Kafka Connect
      # -----------------------------
      GROUP_ID: "1"

      BOOTSTRAP_SERVERS: kafka:29092


      # -----------------------------
      # Kafka Connect internal topics
      # -----------------------------
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_status

      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1


      # -----------------------------
      # Converters
      # -----------------------------
      KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter

      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      KEY_CONVERTER_SCHEMAS_ENABLE: "false"

      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"


      # -----------------------------
      # REST API
      # -----------------------------
      REST_HOST_NAME: 0.0.0.0

      REST_ADVERTISED_HOST_NAME: debezium-connect

    networks:
      - banking-network


# ===========================================================
# VOLUMES
# ===========================================================
volumes:

  postgres-transaction-data:

  redis-data:

  postgres-auth-data:

  postgres-account-data:


# ===========================================================
# NETWORK
# ===========================================================
networks:

  banking-network:
    driver: bridge