CREATE SCHEMA IF NOT EXISTS banking;


CREATE SCHEMA IF NOT EXISTS banking;

CREATE TABLE banking.users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    first_name          VARCHAR(255) NOT NULL,

    last_name           VARCHAR(255) NOT NULL,

    email               VARCHAR(255) NOT NULL UNIQUE,

    password            VARCHAR(255) NOT NULL,

    phone_number        VARCHAR(50)  NOT NULL,

    profile_image       VARCHAR(500),

    role                VARCHAR(50)  NOT NULL DEFAULT 'CUSTOMER',

    permissions         VARCHAR(50)         NOT NULL,

    status              VARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',

    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_date        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    deleted_at          TIMESTAMP,

    suspended_at        TIMESTAMP
);


-- create table banking.users (
--                                id bigint generated by default as identity,
--                                created_at timestamp(6) not null,
--                                deleted_at timestamp(6),
--                                email varchar(255) not null,
--                                first_name varchar(255) not null,
--                                last_name varchar(255) not null,
--                                password varchar(255) not null,
--                                permissions varchar(255) array not null,
--                                phone_number varchar(255) not null,
--                                profile_image varchar(255),
--                                role varchar(255) not null check ((role in ('ADMIN','CUSTOMER'))),
--                                status varchar(255) not null check ((status in ('ACTIVE','INACTIVE','BLOCKED'))),
--                                suspended_at timestamp(6),
--                                updated_date timestamp(6) not null,
--                                primary key (id)
-- )

CREATE TABLE banking.outbox_event
(
    id             UUID PRIMARY KEY,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    type           VARCHAR(255) NOT NULL,
    payload        JSONB        NOT NULL
);

CREATE INDEX idx_outbox_event_aggregate_id
    ON banking.outbox_event (aggregate_id);