spring:
  application:
    name: fraud-detection-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: banking
  datasource:
    url: jdbc:postgresql://localhost:5435/fraud_detection_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true
    validate-on-migrate: true
    default-schema: banking
    schemas: banking
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      properties:
        delivery.timeout.ms: 120000 # 2 minutes timeout for each request
        linger.ms: 0 # 0 ms delay between messages
        request.timeout.ms: 30000 # 30 seconds timeout for each request
#      transaction-id-prefix: fraud-detection-service-${random.value}-
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: fraud-detection-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: java.util.HashMap


server:
  port: 5003

account:
  service:
    url: http://localhost:5001
transaction:
  service:
    url: http://localhost:5006



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    instance:
      hostname: localhost
      prefer-ip-address: false
      instance-id: ${spring.application.name}:${server.port}
      lease-renewal-interval-in-seconds: 10 # The interval at which the Eureka client sends heartbeats to the Eureka server to renew its lease.
      lease-expiration-duration-in-seconds: 30 # The duration after which the Eureka server considers the instance as expired if it doesn't receive a heartbeat.