-- Create schema
CREATE SCHEMA IF NOT EXISTS banking;

-- Create transactions table
CREATE TABLE IF NOT EXISTS banking.transactions (
                                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                    sender_account_number BIGINT NOT NULL,

                                                    receiver_account_number BIGINT NOT NULL,

                                                    transaction_type VARCHAR(50) NOT NULL,

    transaction_status VARCHAR(50) NOT NULL,

    amount NUMERIC(15, 2) NOT NULL,

    description VARCHAR(255),

    failure_reason VARCHAR(255),

    reference_number VARCHAR(255),

    initiated_at TIMESTAMP,

    completed_at TIMESTAMP
    );